General:
  app_name: HotWeir_Calibration
  version: 1.0.0

Calibration_File:
  #File name of the calibration file. "10017-10024" means from 10017 to 10024
  file_number: 10017-10024

Polyfit_Parameter:
  #The corresponding motor speed. Note: one calibrated file number should correspond to one wind speed.
  Corresponding_windSpeed: 0 10 15 20 25 30 35 30

  #Use this if using the same wind tunnel. Note: 0hz has been set to 0m/s wind speed.
  WindSpeed_relationship: y=0.1726x-0.06956

  #Polyfit_degree
  Polyfit_degree: 3